name: cabai_care
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  camera: ^0.12.0+1
  image: ^4.8.0
  image_picker: ^1.2.1
  image_network: ^2.6.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  path: ^1.9.1
  persistent_bottom_nav_bar_v2:  ^6.3.2
  tflite_flutter: ^0.12.1
  google_fonts: ^8.1.0
  shared_preferences: ^2.5.5
  ultralytics_yolo: ^0.3.4
  change_app_package_name: ^1.5.0

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/cabaicare.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#E9EFEF" # Warna hijau gelap khas CabaiCare sebagai background

  android_12:
    color: "#E9EFEF" #  PENTING: Ini yang akan menghilangkan layar hitam di HP Infinix-mu!

  android: true
  ios: false

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.7


flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-ExtraLightItalic.ttf
          weight: 200
          style: italic

    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500

    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Light.ttf
          weight: 300

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

  assets:
    - assets/models/yolov8n_train5.tflite
    - assets/models/labels.txt
    - assets/images/
    - assets/icons/